//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EqDemo.MainForm.Resources", typeof(MainForm_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnExportCsv_Image {
            get {
                object obj = ResourceManager.GetObject("btnExportCsv.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnExportExel_Image {
            get {
                object obj = ResourceManager.GetObject("btnExportExel.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=234,Y=17}.
        /// </summary>
        internal static System.Drawing.Point contextMenu1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenu1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=463,Y=17}.
        /// </summary>
        internal static System.Drawing.Point dataModel1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("dataModel1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EntPanel_ImageAddColumns {
            get {
                object obj = ResourceManager.GetObject("EntPanel.ImageAddColumns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EntPanel_ImageAddConditions {
            get {
                object obj = ResourceManager.GetObject("EntPanel.ImageAddConditions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EntPanel_ImageSelectAll {
            get {
                object obj = ResourceManager.GetObject("EntPanel.ImageSelectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EntPanel_ImageSelectNone {
            get {
                object obj = ResourceManager.GetObject("EntPanel.ImageSelectNone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyQuery can work with different databases and SQL syntax formats.  Change &quot;Database type&quot; to switch between different types of models. Please note: Entity SQL will be generated for &quot;Entity Framework&quot; database type.
        ///.
        /// </summary>
        internal static string labelDbTypeHint_Text {
            get {
                return ResourceManager.GetString("labelDbTypeHint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=658,Y=17}.
        /// </summary>
        internal static System.Drawing.Point openFileDlg_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openFileDlg.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=572,Y=17}.
        /// </summary>
        internal static System.Drawing.Point query1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("query1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=138,Y=17}.
        /// </summary>
        internal static System.Drawing.Point ResultDS_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("ResultDS.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=356,Y=17}.
        /// </summary>
        internal static System.Drawing.Point saveFileDlg_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("saveFileDlg.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=891,Y=16}.
        /// </summary>
        internal static System.Drawing.Point toolTipCsv_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTipCsv.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=780,Y=16}.
        /// </summary>
        internal static System.Drawing.Point toolTipExel_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTipExel.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
