'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class _202101141900542_IntitalCreate
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EqDemoWinFormsNet4VB.202101141900542_IntitalCreate", GetType(_202101141900542_IntitalCreate).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dbo.
        '''</summary>
        Public Shared ReadOnly Property DefaultSchema() As String
            Get
                Return ResourceManager.GetString("DefaultSchema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to H4sIAAAAAAAEAO1dW2/cuBV+L9D/IMxTW2Q9tlMU22C8C8eOu0aT2PU4ad8CWqLHwuoykTiGjWJ/WR/6k/oXSurCOyWSkmYmgeEXDy/focjDc6hD8tP//vPfxc9PaRI8wqKM8+xkdnRwOAtgFuZRnK1OZht0/8OPs59/+v3vFu+i9Cn43JZ7Tcrhmll5MntAaP1mPi/DB5iC8iCNwyIv83t0EObpHET5/Pjw8K/zo6M5xBAzjBUEi5tNhuIUVj/wz7M8C+EabUDyIY9gUjbpOGdZoQYfQQrLNQjhyezd13OY5rPgNIkBlr6Eyf0sAFmWI4Bw2958KuESFXm2Wq5xAkhun9cQl7sHSQmbNr9hxW2bf3hMmj9nFVuocFOiPHUEPHrd9Mdcru7VqzPaX7jH3uGeRc/kqateO5mdAQRXefE8C2Rhb86SghRsO/WgLfoqaBL+Ce8u8iItP789OI0eAR6laAlBET68orqAVYb8vQrONgnaFPAkgxtUgORVcL25 [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property Target() As String
            Get
                Return ResourceManager.GetString("Target", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
